zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  routes:
    hello-server:
      path: /server/**
      url: http://localhost:8071
    hello-client:
      path: /client/**
      serviceId: HELLO-CLIENT

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance:
    hostname: localhost

server:
  port: 8079

spring:
  application:
    name: zuul-service

management:
  endpoints:
    web:
      exposure:
        include: '*'

# Increase the Hystrix timeout to 60s (for all)
hystrix:
  dashboard:
    proxy-stream-allow-list: '**'
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000